---
version: 3
options:
  package_manager_path: /usr/bin/microdnf


images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-supported-rhel8:latest
dependencies:
  galaxy: 
    collections: 
      - name: community.vmware
  python:
    - pyvmomi

